### PR TITLE
Wrap all server actions in Sentry.withServerActionInstrumentation

### PR DESCRIPTION
**Pull request by markspolakovs**
Sentry doesn't do it automatically (https://github.com/getsentry/sentry-javascript/issues/9458)

### CODE REVIEW

**Comment by markspolakovs** [comment]
You probably want to review this with "hide whitespace changes" selected
image

**Comment by markspolakovs** [comment]
Clicked around the PR preview, most key functions work as they used to.

**Comment by markspolakovs** [comment]
And I can see the data coming through in Sentry:
image
Unfortunately it doesn't associate it with the user, need to work out if there's a good way of doing that.

**Review by archessmn — APPROVED** [review]
I'm assuming this is just for tracking these actions in sentry? Seems legit to me but perhaps having some docs about how all of the Sentry stuff would be good to have in the future (not now, happy for this to be merged).

**Comment by markspolakovs** [comment]
> I'm assuming this is just for tracking these actions in sentry? Seems legit to me but perhaps having some docs about how all of the Sentry stuff works would be good to have in the future (not now, happy for this to be merged).

And getting meaningful error reports from them.

**Pull request merged**
