### PR TITLE
[INT-199] Add titles to pages to differentiate tabs

### PR DESCRIPTION
**Pull request by archessmn**
As the title says, just add some titles to pages including event names on event pages.

I also added a back button to the feedback page lol.

### CODE REVIEW

**Comment by archessmn** [comment]
I mean this works for now, we can always just change it later on, probably just changing the hook call to rendering a `<title>` instead?

**Comment by markspolakovs** [comment]
Or alternatively using react-helmet, which would have the benefit of not needing an extra layer of wrapping/indentation or a custom component.

**Comment by archessmn** [comment]
react-helmet seems to just do the same thing and would still need a custom component to avoid needing to change the suffix everywhere if we update it, unless I'm missing something. What I have done is removed the silly JS hook because you can just set the `<title>` tag anywhere and it'll work so it just uses that like helmet would.

**Comment by markspolakovs** [comment]
Are you sure that works as of the version of next we're on? If so go ahead and merge

**Comment by archessmn** [comment]
Works in the PR build and locally so I don't see why it wouldn't work in prod since it's built the same :shrug:

**Pull request merged**
